// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireIdempotencyKey = `-- name: AcquireIdempotencyKey :one
INSERT INTO idempotency_keys (key, withdrawal_id, created_at, expires_at)
VALUES ($1, $2, NOW(), NOW() + INTERVAL '1 second' * $3)
ON CONFLICT (key) DO UPDATE
SET withdrawal_id = EXCLUDED.withdrawal_id,
    expires_at = EXCLUDED.expires_at,
    created_at = EXCLUDED.created_at
WHERE idempotency_keys.expires_at <= NOW()
RETURNING key, withdrawal_id, created_at, expires_at
`

type AcquireIdempotencyKeyParams struct {
	Key          string      `json:"key"`
	WithdrawalID pgtype.Text `json:"withdrawal_id"`
	Column3      interface{} `json:"column_3"`
}

func (q *Queries) AcquireIdempotencyKey(ctx context.Context, arg AcquireIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, acquireIdempotencyKey, arg.Key, arg.WithdrawalID, arg.Column3)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.WithdrawalID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE key = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, key)
	return err
}

const existsIdempotencyKey = `-- name: ExistsIdempotencyKey :one
SELECT EXISTS (
    SELECT 1 FROM idempotency_keys 
    WHERE key = $1 AND expires_at > NOW()
)
`

func (q *Queries) ExistsIdempotencyKey(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, existsIdempotencyKey, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, withdrawal_id, created_at, expires_at FROM idempotency_keys WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.WithdrawalID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE key = $1
`

func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, key)
	return err
}

const storeIdempotencyKey = `-- name: StoreIdempotencyKey :one
INSERT INTO idempotency_keys (key, withdrawal_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING key, withdrawal_id, created_at, expires_at
`

type StoreIdempotencyKeyParams struct {
	Key          string             `json:"key"`
	WithdrawalID pgtype.Text        `json:"withdrawal_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) StoreIdempotencyKey(ctx context.Context, arg StoreIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, storeIdempotencyKey,
		arg.Key,
		arg.WithdrawalID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.WithdrawalID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
