// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	Key          string             `json:"key"`
	WithdrawalID pgtype.Text        `json:"withdrawal_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type ProcessingLock struct {
	WithdrawalID string             `json:"withdrawal_id"`
	LockedBy     pgtype.Text        `json:"locked_by"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Withdrawal struct {
	ID                string             `json:"id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	UserID            string             `json:"user_id"`
	Asset             string             `json:"asset"`
	Amount            string             `json:"amount"`
	DestinationAddr   string             `json:"destination_addr"`
	Network           string             `json:"network"`
	Status            string             `json:"status"`
	RetryCount        int32              `json:"retry_count"`
	MaxRetries        int32              `json:"max_retries"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	TxHash            pgtype.Text        `json:"tx_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
	ProcessingVersion int64              `json:"processing_version"`
}
