// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AcquireIdempotencyKey(ctx context.Context, arg AcquireIdempotencyKeyParams) (IdempotencyKey, error)
	AcquireProcessingLock(ctx context.Context, arg AcquireProcessingLockParams) (ProcessingLock, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	DeleteExpiredProcessingLocks(ctx context.Context) error
	DeleteIdempotencyKey(ctx context.Context, key string) error
	DeleteWithdrawal(ctx context.Context, id string) error
	ExistsIdempotencyKey(ctx context.Context, key string) (bool, error)
	ExtendProcessingLock(ctx context.Context, arg ExtendProcessingLockParams) (ProcessingLock, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetPendingWithdrawals(ctx context.Context, limit int32) ([]Withdrawal, error)
	GetWithdrawalByID(ctx context.Context, id string) (Withdrawal, error)
	GetWithdrawalByIdempotencyKey(ctx context.Context, idempotencyKey string) (Withdrawal, error)
	IsProcessingLocked(ctx context.Context, withdrawalID string) (bool, error)
	ListWithdrawalsByStatus(ctx context.Context, arg ListWithdrawalsByStatusParams) ([]Withdrawal, error)
	ListWithdrawalsByUserID(ctx context.Context, arg ListWithdrawalsByUserIDParams) ([]Withdrawal, error)
	ReleaseIdempotencyKey(ctx context.Context, key string) error
	ReleaseProcessingLock(ctx context.Context, arg ReleaseProcessingLockParams) error
	StoreIdempotencyKey(ctx context.Context, arg StoreIdempotencyKeyParams) (IdempotencyKey, error)
	UpdateWithdrawal(ctx context.Context, arg UpdateWithdrawalParams) (Withdrawal, error)
	UpdateWithdrawalWithVersion(ctx context.Context, arg UpdateWithdrawalWithVersionParams) (Withdrawal, error)
}

var _ Querier = (*Queries)(nil)
